codecov:
  require_ci_to_pass: yes
  max_report_age: 24

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

ignore:
  - "localLLM/src/*"  # Ignore C++ source files
  - "localLLM/man/*"  # Ignore documentation
  - "backend/*"         # Ignore backend directory
  - "custom_files/*"    # Ignore custom files
  - "*.tar.gz"          # Ignore package archives
  - "test_*.R"          # Ignore test scripts in root
  - "*.csv"             # Ignore CSV files
  - "*.md"              # Ignore markdown files

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false